<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>
<?php  $_order = $block->getOrder() ?>
<div class="actions-toolbar">
    <?php if ($_order->getTracksCollection()->count()) : ?>
        <?= $block->getChildHtml('track-all-link') ?>
    <?php endif; ?>
    <a href="<?= $block->escapeUrl($block->getPrintAllShipmentsUrl($_order)) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?= $block->escapeHtml(__('Print All Shipments')) ?></span>
    </a>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment) : ?>
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Shipment #')) ?><?= $block->escapeHtml($_shipment->getIncrementId()) ?></strong>
        <a href="<?= $block->escapeUrl($block->getPrintShipmentUrl($_shipment)) ?>"
           onclick="this.target='_blank'"
           class="action print">
            <span><?= $block->escapeHtml(__('Print Shipment')) ?></span>
        </a>
        <a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($_shipment)) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
           class="action track">
            <span><?= $block->escapeHtml(__('Track this shipment')) ?></span>
        </a>
    </div>
    <?php $tracks = $_shipment->getTracksCollection(); ?>
    <div class="table-wrapper order-items-shipment">
        <table class="data table table-order-items shipment" id="my-shipment-table-<?= (int) $_shipment->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Shipped')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                    <th class="col qty"><?= $block->escapeHtml(__('Qty Shipped')) ?></th>
                    <th class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_shipment->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
    <?= $block->getCommentsHtml($_shipment) ?>
<?php endforeach; ?>
