<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\ProductAlert\Block\Email\Stock */
$helper = $this->helper(Lg\CheckoutHelper\Helper\Data::class);
?>
<?php if ($_products = $block->getProducts()) : ?>
    <p><?= $block->escapeHtml(__('In stock alert! We wanted you to know that these products are now available:')) ?></p>
    <table>
    <?php foreach ($_products as $_product) : ?>
        <?php
            $productData = $_product->getData();
            $productImg = $productData['remote_image_url_1'];
        ?>
        <tr>
            <td class="col photo">
                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?= $block->escapeHtml($_product->getName()) ?>" class="product photo">
                    <img src="<?php echo $productImg; ?>" style="width: 100px; height:100px;" />
                </a>
            </td>
            <td class="col item" style="padding-left: 20px;">
                <p class= "mail-product-info" style="padding-left: 20px;">
                    <strong class="product name">
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"><?= $block->escapeHtml($_product->getName()) ?></a>
                    </strong>
                </p>
                <?php if ($shortDescription = $block->getFilteredContent($_product->getShortDescription())) : ?>
                    <p><small><?= /* @noEscape */  $shortDescription ?></small></p>
                <?php endif; ?>
                <?= $helper->getFormatedPrice($_product); ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php $block->escapeUrl($block->getProductUnsubscribeUrl($_product->getId()))?>
    <p><a href="<?= $block->escapeUrl($block->getUnsubscribeUrl()) ?>" style="color: red"><?= $block->escapeHtml(__('Unsubscribe from all stock alerts')) ?></a></p>
<?php endif; ?>
