<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block <?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
    <div class="block-title <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-title"><h2><?= /* @escapeNotVerified */ $block->getBlockTitle() ?></h2></div>
    <div class="block-content <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-content">
        <?= $block->getChildHtml() ?>
    </div>
</div>
