<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $_item \Magento\Sales\Model\Order\Item */

?>

<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
<?php $_items = $_order->getAllItems(); ?>
<table class="email-items">
    <thead>
    <tr>
        <th class="item-info">
            <?= $block->escapeHtml(__('Items')) ?>
        </th>
        <th class="item-qty">
            <?= $block->escapeHtml(__('Qty')) ?>
        </th>
    </tr>
    </thead>
    <?php foreach ($_items as $_item) : ?>
        <?php if (!$_item->getParentItem()) : ?>
            <tbody>
            <tr class="item_row">
                <?php
                $aSku = explode('.', $_item->getSku());
                unset($aSku[0]);
                $sku = implode('.', $aSku);
                ?>
                <td><p style="font-weight: bold;"><?php echo $_item->getName();?></p><p>SKU: <?php echo $sku; ?></p></td>
                <td style="text-align:center !important"> <?php echo $_item->getQtyOrdered() *1 ; ?></td>
            </tr>
            </tbody>
        <?php endif; ?>
    <?php endforeach; ?>
</table>
<?php endif; ?>
