<script type="text/javascript">
    var paypalDigitalRiverJs;
	function drPaypalLoader(){
        if (!digitalRiverInitiator) {
            return;
        }
        paypalDigitalRiverJs = digitalRiverInitiator.getDigitalRiverJs();
	}

	function continuePaypalOrder()
	{
		require(["jquery"], function ($) {		
			var edit = '<?php echo $block->escapeJs($block->escapeHtml(__('Edit')));?>';
			var title = "<div class='title'>"+$(".payment-methods .payment-group .payment-method._active .payment-method-title .label span").html()+"</div>";
			var editlink = "<a class='payment-edit' href='javascript:void(0)' id='payment-edit-paypal' onclick='displayPaypalForm()'>"+edit+"</a>";
			$("#payment-data_paypal").html(title+editlink);						
			$("#payment-data_paypal").css("display","block");
			$("#payment-data_paypal").addClass('payment-active');
			$(".paypal-btn-first").css("display","none");
			jQuery('#payment-container .section-container')
				.css('background','#e6e6e6')
				.css('padding','0 30px');
			jQuery('#payment-data_paypal').parents('.payment-method-content')
                .find('.checkout-agreements-block')
                .show();
			$(".paypal-btn-second").css("display","block");
			$(".paypal-btn-second .checkout").css("display","block");
			$(".payment-methods .payment-group .step-title").css("display","none");
			$(".payment-method._active .payment-method-content .payment-method-note").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-method-title").css("display","none");
			$(".payment-methods .payment-group .payment-method .details").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-logos").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-icon").css("display","none");
			$(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","none");
			$("#payframe").css("display","none");
			$('.checkout-tabs .nav-pills li').removeClass('active');
			$('.checkout-tabs .nav-pills li:nth-child(2)').addClass('active');
			$('.payment-method-content').css('margin-bottom','50px');
			if(window.checkoutConfig.quoteData.is_virtual){
				$(".billing-address-details .action-edit-address").css("display","none");
			}else{
				$(".billing-address-details .action-edit-address").css("display","none");
				$(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","none");
			}
		});		
	}	
	function displayPaypalForm(){
		jQuery('#payment-data_paypal').parents('.payment-method-content')
            .find('.checkout-agreements-block')
			.hide();
		jQuery('#payment-container .section-container')
			.css('background','none')
			.css('padding','');
		jQuery(".payment-methods .payment-group .step-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .payment-method-title").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .details").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-logos").css("display","inline-block");
		jQuery(".payment-methods .payment-group .payment-method .payment-icon").css("display","inline-block");
		jQuery("#drpay-paypal-form").css("display","block");
		jQuery("#payment-data_paypal").css("display","none");
		jQuery("#payment-data_paypal").removeClass('payment-active');
		jQuery(".payment-methods .payment-group .payment-method .payment-method-instruction").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .payment-method-content .checkout").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .paypal-btn-first").css("display","block");
		jQuery(".payment-methods .payment-group .payment-method .paypal-btn-first .checkout").css("display","block");
		jQuery('.checkout-tabs .nav-pills li').removeClass('active');
		jQuery('.checkout-tabs .nav-pills li:nth-child(1)').addClass('active');
		jQuery('.payment-method-content').css('margin-bottom','10px');
		jQuery(".payment-methods .payment-group .payment-method .checkout").css("display","none");
		jQuery(".payment-methods .payment-group .payment-method #drpay-creditcard-form .checkout").css("display","block");	
		if(window.checkoutConfig.quoteData.is_virtual){
			jQuery(".billing-address-details .action-edit-address").css("display","block");
		}else{
			jQuery(".billing-address-details .action-edit-address").css("display","block");
			jQuery(".payment-method-billing-address .billing-address-same-as-shipping-block").css("display","block");
		}
	}	
</script>
