<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Squiz.PHP.GlobalKeyword.NotAllowed
?>
<?php
$_order  = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $this->helper(\Magento\Tax\Helper\Data::class)->getCalculatedTaxes($_source);
global $taxIter;
$taxIter++;
?>

<?php if ($_fullInfo && $block->displayFullSummary()) : ?>
    <?php foreach ($_fullInfo as $info) : ?>
        <?php
        $percent    = $info['percent'];
        $amount     = $info['tax_amount'];
        $baseAmount = $info['base_tax_amount'];
        $title      = $info['title'];
        ?>
        <tr class="totals tax details details-<?= (int) $taxIter ?><?= ($block->getIsPlaneMode()) ? ' plane' : '' ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?>>
                <?=__('Tax')?>
                <br />
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?> rowspan="1">
                <?= /* @noEscape */ $_order->formatPrice($amount) ?>
            </td>
            <td></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
