
<style>
    p{
        line-height: 20px;
        font-size: 10.5pt;
        font-family: Calibri !important;
    }
    .button.refund-button {
        width: 50%;
        display: block;
        text-align: center;
        background-color: #9abaf3;
        color: #000 !important;
        vertical-align: middle;
        padding: 12px;
        margin: 20px auto;
        font-weight: 600;
        border: 1px solid #9e9ed2;
        font-size: 10.5pt;
    }
    .cornflowerblue{
        color: cornflowerblue;
        font-weight: 600;
    }
    h1{
        font-weight: 500 !important;
        color: #000;
        font-size: 19.5pt;
        font-family: Calibri;
    }
</style>