<?php

use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use CyberSource\SecureAcceptance\Block\Customer\CardRenderer;

/** @var CardRenderer|Template $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
$paymentGateway = $block->escapeHtml($block->getPaymentMethodName());

// this function returns the credit card type for a given credit card image url
$getCardType = function($url) {
    $re = '/(vi|mc|ae|di|jcb|mi|dn).(?:png|jpg|gif)$/mi';
    $str = $url;
    $matches = [[]];
    $cardCode = "";
    $ret = "";
    
    if(preg_match_all($re, $str, $matches)) {
        $cardCode = strtoupper($matches[1][0]);
    }

    // found in vendor\cybersource\module-secure-acceptance\Block\Checkout\Billing.php
    $lookup = [
        'VI' => ['code' => '001', 'name' => 'Visa'],
        'MC' => ['code' => '002', 'name' => 'MasterCard'],
        'AE' => ['code' => '003', 'name' => 'American Express'],
        'DI' => ['code' => '004', 'name' => 'Discover'],
        'JCB' => ['code' => '007', 'name' => 'JCB'],
        'MI' => ['code' => '042', 'name' => 'Maestro International'],
        'DN' => ['code' => '005', 'name' => 'Diners Club'],
    ];

    if(array_key_exists($cardCode, $lookup)) {
       if(isset($lookup[$cardCode]["name"])) {
            $ret = $lookup[$cardCode]["name"];
       }; 
    }

    return $ret;
} 

?>
<tr>
    <td data-th="<?php echo $block->escapeHtml(__('Payment Gateway')) ?>" class="col card-number">
        <?php /* @noEscape */ echo $paymentGateway ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?php echo $block->escapeHtml(__('ending')); ?></span> <?php /* @noEscape */ echo $ccNumberView ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?php echo $block->escapeHtml($block->getExpDate()); ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Type')) ?>" class="col card-type">
        <img src="<?php /* @noEscape */ echo $block->getIconUrl(); ?>"
             alt="<?php /* @noEscape */ echo $getCardType($block->getIconUrl()); ?>"
             width="<?php /* @noEscape */ echo $block->getIconWidth(); ?>"
             height="<?php /* @noEscape */ echo $block->getIconHeight(); ?>"
        >
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?php echo $block->escapeUrl($block->getUrl('vault/cards/deleteaction')); ?>"
            method="post"
            >
            <?php echo $block->getBlockHtml('formkey')?>
            <input
                name="<?php /* @noEscape */ echo PaymentTokenInterface::PUBLIC_HASH?>"
                value="<?php /* @noEscape */ echo $block->getToken()->getPublicHash()?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?php echo $block->escapeHtml(__('Delete')) ?>",
                                        "content": "Are you sure you want to delete this card: <?php
                                            /* @noEscape */ echo $ccNumberView
                                        ?>?"
                                    }
                                }'>
                <span><?php echo $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
