
<?php
// @codingStandardsIgnoreFile

/** @var $block  \Lg\CheckoutHelper\Block\Cart\Item\Renderer */
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
// Check stock item
$existingChildrenIds = $block->getProductParent($product->getId());
$isSalebleQuantity = $block->getSalebleQuantity($existingChildrenIds, (int)$_item->getQty());
$isProductOfWebsite = true;
$storeCode =  explode('.', $product->getSku())[0];
if(strtoupper($storeCode) != strtoupper($product->getStore()->getCode())){
    $isProductOfWebsite = false;
}
$components = $block->getComponentsPto($product->getSku());
$canDisplayPrePurchaseNotice =  $block->canDisplayPrePurchaseNotice();
$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');

?>

<div id="cart-item-default" data-bind="scope:'cart-item-default'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-item-default": {
                    "Magento_Ui/js/core/app": {
                    "components": {
                            "cart-item-default": {
                                "component": "Magento_Checkout/js/view/cart/item/default"
                            }
                        }
                    }
                }
            }
        </script>
</div>


<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item it-cart">
        <div class="product-img-shopping-cart" >
            <?php if ($block->hasProductUrl()):?>
            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        </div>
        <div class="product-item-details" >
            <?php if ($canDisplayPrePurchaseNotice): ?>
                <div class="pre-purchased-label flag-pre-order">
                    <span><?= $block->escapeHtml($block->getPrePurchaseLabel()) ?></span>
                </div>
            <?php endif; ?>
            <div class="sku"><?= $block->escapeHtml($product->getData('model_name')) ?></div>
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if (!empty($components)) : ?>
                <div class="pto-components">
                    <strong class="comp-label"><?= __('View Components'); ?>&nbsp;</strong>
                    <ul class="model-name-comp">
                        <?php foreach ($components as $component) : ?>
                            <li><?= $component ?></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            <?php endif; ?>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($canDisplayPrePurchaseNotice): ?>
                <div class="pre-purchased-text purchase-note">
                    <span><?= $block->escapeHtml($block->getPrePurchaseText()) ?></span>
                </div>
            <?php endif; ?>
            <?php if (($messages = $block->getMessages()) && $isProductOfWebsite): ?>
                <?php foreach ($messages as $message): ?>
                    <?php if ($isProductOfWebsite ): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <select id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                    name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                    data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                    title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                    class="qty"
                    data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                    data-role="cart-item-qty"
                    data-cart-item-update
                    onchange="this.form.submit()">
                <?php $i = 1; ?>

                <?php
                $itemsLimit = (int)$block->getData('maximum');

                while($i <= $itemsLimit) { ?>
                    <?php $optionSelected = $block->getQty() == $i ? ' selected' : ''; ?>
                    <option value="<?= $i; ?>"<?= $optionSelected; ?>><?= $i; ?></option>
                    <?php $i++; ?>
                <?php } ?>
            </select>

            <a onclick="eventRemoveItem(<?= $product->getId() ?>)" href="#" title="<?= $block->escapeHtml(__('Remove item')) ?>" class="action visible-mobile action-delete" data-post='<?= /* @noEscape */ $cartHelper->getDeletePostJson($block->getItem()) ?>'>
                <span class="mobile-delete-svg"></span>
            </a>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td class="col edit" data-th="<?= $block->escapeHtml(__('Edit')) ?>">
        <div class="actions-toolbar">
            <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
<tr>
    <td colspan="5">
        <div data="sku-<?= $block->escapeHtml($_item->getSku()) ?>" class="messages-item"></div>
    </td>
</tr>

<?php if ($_item->getExtensionAttributes()->getIsInnovelItem()) : ?>
    <tr>
        <td colspan="4">
            <div class="installation-haulaway-container">
                <?= $block->getChildHtml('installation_haulaway'); ?>
            </div>
        </td>
    </tr>
<?php endif; ?>

<?=$block->getChildHtml('measure_first', false);?>
</tbody>