<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<style>
    .sales-order-view .page-title-wrapper .order-date, .magento_rma-returns-view .page-title-wrapper .order-date, .sales-order-invoice .page-title-wrapper .order-date, .magento_rma-returns-invoice .page-title-wrapper .order-date, .sales-order-shipment .page-title-wrapper .order-date, .magento_rma-returns-shipment .page-title-wrapper .order-date, .sales-order-creditmemo .page-title-wrapper .order-date, .magento_rma-returns-creditmemo .page-title-wrapper .order-date, .sales-order-returns .page-title-wrapper .order-date, .magento_rma-returns-returns .page-title-wrapper .order-date{
        vertical-align: bottom !important;
    }
</style>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= htmlspecialchars_decode($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item options">
                <?php foreach ($_options as $_option) : ?>
                    <?php if ($block->escapeHtml($_option['label']) != 'objet_sales_combine_id'
                        && $block->escapeHtml($_option['label']) != 'objet_sales_options') : ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <?php endif; ?>
                    <?php if (!$block->getPrintStatus()) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) && $_option['label'] != 'objet_sales_combine_id' ? ' class="tooltip wrapper"' : '') ?>>
                            <?php if ($block->escapeHtml($_option['label']) != 'objet_sales_combine_id') : ?>
                                <?= $block->escapeHtml($_formatedOptionValue['value']) ?>
                            <?php endif; ?>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <?php if ($_option['label'] != 'objet_sales_combine_id') : ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <?php if ($_option['label'] != 'objet_sales_options') : ?>
                                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                            <?php endif; ?>
                                            <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                    <?php else : ?>
                        <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty Shipped')) ?>"><?= (int) $_item->getQty() ?></td>
    <td class="col status" data-th="<?= $block->escapeHtml(__('Status')) ?>">
        <?= $block->escapeHtml($block->getLineStatus($_item->getOrderItemId())) ?>
    </td>
    <td class="col actions action-custom" data-th="<?= $block->escapeHtml(__('Action')) ?>">
        <?php if ($block->checkRenderTracking($_item->getOrderItemId())) { ?>
            <a class="link" href="<?= $block->getTrackingLink($_item->getOrderItemId()) ?>" target="_blank">
                <?= $block->escapeHtml(__('<tracking id>')) ?>
            </a>
            <?php
        }
        ?>
    </td>
</tr>
