<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<div class="block block-addresses-default">
    <div class="block-title"><h2><?= $block->escapeHtml(__('Default Addresses')) ?></h2></div>

    <div class="block-content">
        <ul>

            <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
                <!--<div class="box box-address-billing">-->
                <li class="box-title box box-billing-address">
                    <h3>
                        <?= $block->escapeHtml(__('Default Billing Address')) ?>
                    </h3>
                    <ul>
                        <li><?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?></li>
                        <li class="box-actions">
                            <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                                <span><?= $block->escapeHtml(__('Change Billing Address')) ?></span>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--</div>-->
            <?php else: ?>
                <!--<div class="box box-billing-address">-->
                <li class="box-title">
                    <h3>
                        <?= $block->escapeHtml(__('Default Billing Address')) ?>
                    </h3>
                    <ul>
                        <li><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></li>
                    </ul>
                </li>
                <!--</div>-->
            <?php endif ?>

            <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
                <!--<div class="box box-address-shipping">-->
                <li class="box-title">
                    <h3>
                        <?= $block->escapeHtml(__('Default Shipping Address')) ?>
                    </h3>
                    <ul>
                        <li>
                            <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                        </li>
                        <li>
                            <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                                <span><?= $block->escapeHtml(__('Change Shipping Address')) ?></span>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--</div>-->
            <?php else: ?>
                <!--<div class="box box-shipping-address">-->
                <li class="box-title">
                    <h3>
                        <?= $block->escapeHtml(__('Default Shipping Address')) ?>
                    </h3>
                    <ul>
                        <li>
                            <?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?>
                        </li>
                    </ul>
                </li>
                <!--</div>-->
            <?php endif ?>
        </ul>
    </div>
</div>